openapi: 3.0.3
info:
  title: Splunk Search API (8089 Port)
  description: Minimal OpenAPI spec for Splunk search initiation and results retrieval
  version: "1.0"
servers:
  - url: https://{host}:8089/services
    variables:
      host:
        default: localhost
        description: Splunk instance hostname/IP

components:
  securitySchemes:
    splunk_session_key:
      type: apiKey
      in: header
      name: Authorization
      description: "Splunk {session_key} - Get from /services/auth/login first"

security:
  - splunk_session_key: []

paths:
  /search/jobs:
    post:
      summary: Create search job
      operationId: createSearchJob
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              required: [search]
              properties:
                search:
                  type: string
                  example: "index=_* | head 10"
                output_mode:
                  type: string
                  enum: [xml, json, csv]
                  default: json
                exec_mode:
                  type: string
                  enum: [oneshot, blocking]
                  default: blocking
      responses:
        '201':
          description: Search job created
          content:
            application/json:
              schema:
                type: object
                properties:
                  sid:
                    type: string
                    example: "1234567890.123"
        '401':
          description: Invalid session key

  /search/jobs/{sid}:
    get:
      summary: Get search job status
      parameters:
        - name: sid
          in: path
          required: true
          schema:
            type: string
            example: "1234567890.123"
      responses:
        '200':
          description: Search job status
          content:
            application/json:
              schema:
                type: object
                properties:
                  entry:
                    type: array
                    items:
                      type: object
                      properties:
                        content:
                          type: object
                          properties:
                            isReady:
                              type: string
                              example: "1"
                            dispatchState:
                              type: string
                              example: "DONE"

  /search/jobs/{sid}/results:
    get:
      summary: Get search results
      parameters:
        - name: sid
          in: path
          required: true
          schema:
            type: string
            example: "1234567890.123"
        - name: output_mode
          in: query
          schema:
            type: string
            enum: [xml, json, csv]
            default: json
        - name: count
          in: query
          schema:
            type: integer
            default: 100
      responses:
        '200':
          description: Search results
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    _time:
                      type: string
                      example: "2026-02-25T16:10:00.000-05:00"
                    _raw:
                      type: string
                      example: "1,2,3,4,5"
